### ISSUE TITLE
Latest Pyro4 hanging when running tests

### ISSUE THREAD

**Issue by Peque** [irmen/Pyro4#129]
Hi Irmen,

This is more a question, rather than an issue (I am not sure if it is a Pyro4 issue yet).

I have a project, [osBrain](https://github.com/opensistemas-hub/osbrain), which uses Pyro4. It worked well with version 4.45. After doing some little changes, `master` works now with 4.46. However, it seems it does not work with 4.47.

The problem is that some tests are now timing out (as if something was blocking). Apparently the tests pass, so the blocking might occur on tear-down (as I am using some `pytest` fixtures that take care of shutting down everything after each test).

Some bisecting tells me the change that introduced this timeouts is in 88f88bf1ccdfaff8c2bbbda8fc032a145d07d44b . In particular, this change in `src/Pyro4/naming.py`:

```diff
@@ -519,7 +523,7 @@ def locateNS(host=None, port=None, broadcast=True, hmac_key=None):
     proxy = core.Proxy(uri)
     proxy._pyroHmacKey = hmac_key
     try:
-        proxy.ping()
+        proxy._pyroBind()
         log.debug("located NS")
         return proxy
     except PyroError as x:
```

Any hints on why could this be happening? or how to avoid it?

Thanks for your help. :blush:

PS: I am tracking this issue [here as well, in my project](https://github.com/opensistemas-hub/osbrain/issues/9). So feel free to close this if you consider it is not a Pyro4-related issue.

**Comment by Peque** [comment]
Also, depending on how I run the tests, I might trigger (or not) the timeouts...

This command triggers the timeouts (some blocking is happening):

    pytest -xsv ./

However, this, does not:

    pytest -xsv ./ --boxed

**Comment by irmen** [comment]
I consider it a Pyro issue for now because upgrading should not break user code unless it's a documented api or behavior change (or unless user code is abusive...)

Hmm it is peculiar. The change on that line at first glance is not relevant to the issue. It is supposed to be just a minor optimization that effectively does the same thing as the old code: checking if the name server is reachable.

Have you confirmed that if you change that single line in your Pyro installation back to proxy.ping() that your problem goes away?

Now thinking of it, there's another more significant change in that commit that is giving me some issues lately and I really think that's the culprit. See #128 : name server lookup now also tries 127.0.1.1 to see if a NS is listening there. It times out on some of my machines.

**Comment by Peque** [comment]
Yeah, the thing is that, although the biggest change in that commit is the 127.0.1.1 related code, the line that is giving me the timeouts is the one I posted above (i.e.: if I change back to `.ping()`, then it works fine).

**Comment by irmen** [comment]
I'll look into it. Is it possible to share a minimal test case that exposes the issue? Would be nice to have a test for this included in Pyro i think

**Comment by Peque** [comment]
I wish I could narrow this down... However, I am still trying to figure out what is happening and how to reduce it to a test case (I am also interested in that for my project).

Here is the thing:

- All tests pass fine (no timeouts) if executed one-by-one (i.e.: `pytest ... -k single_test_X`).
- `pytest -xsv ./` triggers the timeouts.
- `pytest -xsv ./ --boxed` does not trigger the timeouts.

:sweat_smile:

**Comment by irmen** [comment]
does Pyro's test suite run succesfully?

**Comment by irmen** [comment]
Also, here's another idea:

are you launching a name server in your unit test suite?
The change from ping() to _pyrobind() does cause locateNS() to only obtain metadata from the server and not call any remote method.  I don't know what your tests are doing but if you rely on a remote method being called before you can shutdown cleanly, this could be the reason it now hangs.

**Comment by Peque** [comment]
Thank you. I'll check that tomorrow and report back. :blush:

**Comment by Peque** [comment]
All tests pass with 4.46. Some warnings, though (run with Python 3.5):

```
......................................./mnt/ssd_media/src/Pyro4/.tox/py35/lib/python3.5/site-packages/Pyro4/core.py:850: UserWarning: Using @expose with instance mode arguments(s) on a class also automatically exposes all members, which is an unintended side-effect that will be corrected soon. Read the change log in the documentation for more details and what to do.
  warnings.warn("Using @expose with instance mode arguments(s) on a class also automatically "
...................../usr/lib64/python3.5/threading.py:345: ResourceWarning: unclosed <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 54204)>
  waiters_to_notify = _deque(_islice(all_waiters, n))
/usr/lib64/python3.5/threading.py:345: ResourceWarning: unclosed <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 54208)>
  waiters_to_notify = _deque(_islice(all_waiters, n))
........................................................................./mnt/ssd_media/src/Pyro4/.tox/py35/lib/python3.5/site-packages/Pyro4/socketutil.py:346: ResourceWarning: unclosed <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 54214)>
  sock = socket.socket(family, socket.SOCK_DGRAM)
/mnt/ssd_media/src/Pyro4/.tox/py35/lib/python3.5/site-packages/Pyro4/socketutil.py:346: ResourceWarning: unclosed <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 54216)>
  sock = socket.socket(family, socket.SOCK_DGRAM)
/mnt/ssd_media/src/Pyro4/.tox/py35/lib/python3.5/site-packages/Pyro4/socketutil.py:346: ResourceWarning: unclosed <socket.socket fd=10, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0>
  sock = socket.socket(family, socket.SOCK_DGRAM)
............................ss.............................................ss..................s..........s..............sss.s....s..............s......ss.............................s..........................................................................................................................................................
```

With 4.47 I get some warnings as well, although this time we can see some `NamingError("Failed to locate the nameserver")`  (run with Python 3.5):

```
......................................................../mnt/ssd_media/src/Pyro4/.tox/py35/lib/python3.5/site-packages/Pyro4/socketserver/threadpool.py:71: ResourceWarning: unclosed <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 55312)>
  log.debug("worker pool of size %d created", self.num_workers())
/mnt/ssd_media/src/Pyro4/.tox/py35/lib/python3.5/site-packages/Pyro4/socketserver/threadpool.py:71: ResourceWarning: unclosed <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 55316)>
  log.debug("worker pool of size %d created", self.num_workers())
......................................................................./mnt/ssd_media/src/Pyro4/.tox/py35/lib/python3.5/site-packages/Pyro4/naming.py:530: ResourceWarning: unclosed <socket.socket fd=10, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 55328)>
  e = NamingError("Failed to locate the nameserver")
/mnt/ssd_media/src/Pyro4/.tox/py35/lib/python3.5/site-packages/Pyro4/naming.py:530: ResourceWarning: unclosed <socket.socket fd=14, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 55330)>
  e = NamingError("Failed to locate the nameserver")
......./usr/lib64/python3.5/json/encoder.py:257: ResourceWarning: unclosed <socket.socket fd=4, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0>
  return _iterencode(o, 0)
.......................ss.............................................ss..................s..........s..............sss.s....s..............s......ss.............................s..........................................................................................................................................................
```

Note that with Python 2.7 I get only one warning with 4.46 and no warnings with 4.47. It seems Python 3.5 is generating more warnings with the test suite. Can you reproduce the same? Is this expected?

These are the warnings from 88f88bf1ccdfaff8c2bbbda8fc032a145d07d44b (Python 3.5 again):

```
......................................./mnt/ssd_media/src/Pyro4/.tox/py35/lib/python3.5/site-packages/Pyro4/core.py:850: UserWarning: Using @expose with instance mode arguments(s) on a class also automatically exposes all members, which is an unintended side-effect that will be corrected soon. Read the change log in the documentation for more details and what to do.
  warnings.warn("Using @expose with instance mode arguments(s) on a class also automatically "
...................../mnt/ssd_media/src/Pyro4/.tox/py35/lib/python3.5/site-packages/Pyro4/core.py:1350: ResourceWarning: unclosed <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 56540)>
  ser.register_type_replacement(type(obj_or_class), pyroObjectToAutoProxy)
/mnt/ssd_media/src/Pyro4/.tox/py35/lib/python3.5/site-packages/Pyro4/core.py:1350: ResourceWarning: unclosed <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 56544)>
  ser.register_type_replacement(type(obj_or_class), pyroObjectToAutoProxy)
......................................................................../usr/lib64/python3.5/threading.py:345: ResourceWarning: unclosed <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 56550)>
  waiters_to_notify = _deque(_islice(all_waiters, n))
/usr/lib64/python3.5/threading.py:345: ResourceWarning: unclosed <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 56552)>
  waiters_to_notify = _deque(_islice(all_waiters, n))
......../mnt/ssd_media/src/Pyro4/.tox/py35/lib/python3.5/site-packages/Pyro4/core.py:260: ResourceWarning: unclosed <socket.socket fd=4, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0>
  return super(Proxy, self).__setattr__(name, value)  # one of the special pyro attributes
.....................ss.............................................ss..................s..........s..............sss.s....s..............s......ss.............................s..........................................................................................................................................................
```

And the warnings from 88f88bf1ccdfaff8c2bbbda8fc032a145d07d44b replacing `_pyroBind` with `ping`  (Python 3.5 again):

```
......................................./mnt/ssd_media/src/Pyro4/.tox/py35/lib/python3.5/site-packages/Pyro4/core.py:850: UserWarning: Using @expose with instance mode arguments(s) on a class also automatically exposes all members, which is an unintended side-effect that will be corrected soon. Read the change log in the documentation for more details and what to do.
  warnings.warn("Using @expose with instance mode arguments(s) on a class also automatically "
...................../mnt/ssd_media/src/Pyro4/.tox/py35/lib/python3.5/site-packages/Pyro4/util.py:437: ResourceWarning: unclosed <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 57602)>
  def copyreg_function(obj):
/mnt/ssd_media/src/Pyro4/.tox/py35/lib/python3.5/site-packages/Pyro4/util.py:437: ResourceWarning: unclosed <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 57606)>
  def copyreg_function(obj):
......................................................................../usr/lib64/python3.5/threading.py:224: ResourceWarning: unclosed <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 57612)>
  self._release_save = lock._release_save
/usr/lib64/python3.5/threading.py:224: ResourceWarning: unclosed <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 57614)>
  self._release_save = lock._release_save
......../mnt/ssd_media/src/Pyro4/.tox/py35/lib/python3.5/site-packages/Pyro4/core.py:260: ResourceWarning: unclosed <socket.socket fd=4, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0>
  return super(Proxy, self).__setattr__(name, value)  # one of the special pyro attributes
.....................ss.............................................ss..................s..........s..............sss.s....s..............s......ss.............................s..........................................................................................................................................................
```

Don't know if any of this is useful for you, in case not, sorry for the spam.

**Comment by Peque** [comment]
> **irmen**
> are you launching a name server in your unit test suite?
> The change from ping() to _pyrobind() does cause locateNS() to only obtain metadata from the server and not call any remote method. I don't know what your tests are doing but if you rely on a remote method being called before you can shutdown cleanly, this could be the reason it now hangs.

Yes I am, several (usually one per test), each in a random address. I do not rely on a remote method being called before I can shutdown cleanly, though.

However, I thought about what could be the difference between `_pyroBind()` and `ping()`, and tried this stupid thing in `src/Pyro4/core.py`:

```diff
@@ -370,6 +370,8 @@ class Proxy(object):
         will be updated with a direct PYRO uri, if it isn't one yet.
         If the proxy is already bound, it will not bind again.
         """
+        import time
+        time.sleep(0.01)
         return self.__pyroCreateConnection(True)
 
     def __pyroGetTimeout(self):
```

And all tests pass without any timeouts/blocking from 88f88bf1ccdfaff8c2bbbda8fc032a145d07d44b. If I try the same "fix" in 4.47 it works well too. So it seems my tests are failing because `_pyroBind()` is too fast? :astonished:

**Comment by irmen** [comment]
This could prove to be a difficult one to track down. But I recall having similar issues when running unit tests where the test depends on something happening in a background thread. I suppose you're launching the name server in a thread. The tests may hang/stall because the main thread is not yielding or holding the GIL too long so the name server may never have a chance to reply.
Sometimes indeed inserting a simple time.sleep(0.01) in your unit test code is enough to make the test thread yield to the name server thread and make the test complete.  See what I've done in test_naming.py


I'll look into the warnings you posted above later.

**Comment by Peque** [comment]
Thanks. I will report back if I find anything new about this (or if I can reduce it to a simple test case).

I checked in case it could be a problem with my specific setup/virtualenvironment, but if you look at your Travis logs you will see there are also a couple of warnings when running the tests with Python 3.

**Comment by irmen** [comment]
The warning by pyro 4.46 itself about @expose is because of the pending changes regarding said decorator. With 4.47 the API transition is complete and the warning should be gone. 

The resource warnings are caused by Python itself and I have them as well. I think Python 3.2 introduced them.  They're harmless (as far as I know) and are caused by not really clean teardowns in the unit test suite. It's pretty hard to cleanly shutdown a thread based socket server and I think the resource warnings are caused by a not-so-clean shutdown. 

I've just committed a fix for my 127.0.1.1 timeout problem, can you perhaps try your code against the latest master and let me know if your issue persists?

**Comment by Peque** [comment]
The issue still persists even with the latest changes.

I think it might be related to those not-really-clean teardowns/shutdowns, because my tests block/timeout on teardown/shutdown as well and it all started when those warnings first appeared in Pyro4 tests.

**Comment by irmen** [comment]
That's not nice. Have you tried adding time.sleep() calls in your own tests ?

As I don't have anything to reproduce the issue with, it's hard to find a cause at this time...

**Comment by Peque** [comment]
> That's not nice. Have you tried adding time.sleep() calls in your own tests ? Also, I don't think the resource warnings have anything to do with the problem because earlier you were writing that the _pyroBind() instead of ping() seems to cause the issue

My tests work fine after some "tweaks", yeah. I said the warnings could be the reason why my tests started failing because they failed on shutdown/teardown (and those warnings appear on shutdown/teardown as well). Of course, the problem is not really the `_pyroBind()` vs. `ping()` thing, as a `time.sleep()` call seemed to "fix" it. So it _may_ be related to those warnings, somehow...

> As I don't have anything to reproduce the issue with, it's hard to find a cause at this time...

I understand. Feel free to close this issue. I will keep one opened in my own project. I will try to investigate this further and create a reproducible, simplified case. But, me too, I don't think I will find the time until, probably, next month.

When I find something new about this issue, I will write here for the issue to be reopened (if necessary).

**Comment by irmen** [comment]
I managed to find and fix the cause of the ResourceWarnings (see 02ce8459bab04b30104a11f3b5453adebccdc986)

**Comment by Peque** [comment]
Thanks a lot for your help and for taking the time to fix those warnings. :blush:

The problem still persist, though. So, once again, feel free to close this issue. Once I find a minimal reproducible test case, I will share it with you (to reopen the issue if necessary).

**Comment by irmen** [comment]
Very well, I'll close this for now.

In the meantime here's the list of changes between 4.46 and 4.47 in detail, perhaps it helps to pin down the cause:   https://github.com/irmen/Pyro4/compare/4.46...4.47
